---
title: "ANCOMBC2"
output: html_document
date: "2024-06-06"
---

```{r}
getwd()
#setwd("H:/")
```
```{r}
#if (!requireNamespace("BiocManager", quietly = TRUE))install.packages("BiocManager")
#BiocManager::install("ANCOMBC")
library(ANCOMBC)

#BiocManager::install("phyloseq")
library(phyloseq)
library(tibble)
#BiocManager::install("microbiome")
library(microbiome)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lme4)
#install.packages("DT")
library(DT)
```

load data
```{r}
#Clean ASV dataset
ASVs <- read.table("~/Data/Data_analysis_ANCOMBC2/Megablast_Philemon_dada2_UNITE_no0_ASVNumbers2.txt", header = T, sep="\t", dec=".", fill = FALSE)
head(ASVs)
dim(ASVs)

#Clean ASV dataset rarefied
ASV2 <- read.table("~/Data/Data_analysis_ANCOMBC2/ASV_ITS_Rarefied_Table_1000_times_clean_ASVnumbers.txt", header = T, sep="\t", dec=".", fill = FALSE)
head(ASV2)
dim(ASV2)
#switch rows and columns
ASV2 <- t(ASV2)

#Taxonomy file
tax <- read.table("~/Data/Data_analysis_ANCOMBC2/Megablast_Philemon_dada2_Unite_taxonomy_CLEAN.txt", header = T, sep="\t", dec=".", fill = FALSE)
head(tax)
dim(tax)

#metadata file
metadata <- read.table("~/Data/Data_analysis_ANCOMBC2/Metadata_Philemon_ITS3.txt", header = T, sep="\t", dec=".", fill = FALSE)
head(metadata)
dim(metadata)
```
Create Phyloseq-Object with rarefied data (nach Schloss 2024)
```{r}
#make rownames
metadata <- metadata %>%
    tibble::column_to_rownames("ID")

rownames(tax) <- tax[, 1]
tax <- tax[, -1]
head(tax)

#Create matrix
tax_mat <- as.matrix(tax)
ASVs_mat <- as.matrix(ASV2)

#Create PhyloSeq object
ASV = otu_table(ASVs_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(metadata)

Tomicro <- phyloseq(ASV, TAX, samples)
Tomicro
```
```{r}
#we consider the following covariates:
#Continuous covariates: none, could be for example: “age”
#Categorical covariates: “plant.condition” (2 levels), “soil” (2 levels), "compartment" (3 levels)
#The group variable of interest: “soil”
#Two groups: “A”, “B”
#(The reference group: “A”)

## Transform data from phyloseq object into tree summarized object
Tomicro_tse <- mia::makeTreeSummarizedExperimentFromPhyloseq(Tomicro)
print(Tomicro_tse)
```
https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html 
https://bioconductor.org/packages/release/bioc/manuals/ANCOMBC/man/ANCOMBC.pdf

```{r}
#run anbombc2 (using tree summarized experiments; it is also possible to import data in phyloseq format)
set.seed(2608)

output = ancombc2(data = Tomicro_tse, assay_name = "counts", tax_level = "phylum",
                  fix_formula = "Compartment+Soil.origin+Plant.condition", 
                  rand_formula = NULL,
                  p_adj_method = "hochberg", 
                  group = "Compartment", 
                  alpha = 0.05, n_cl = 2, 
                  struc_zero = TRUE,
                  global = TRUE, pairwise = TRUE, 
                  dunnet = TRUE, trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                      verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  #lme_control = NULL, 
                  mdfdr_control = list(fwer_ctrl_method = "hochberg", B = 100), 
                  trend_control = NULL)
```

```{r}
#detection of structural zeros (taxon presence/absence) presence = FALSE, absence = TRUE
tab_zero = output$zero_ind
tab_zero %>%
  datatable(caption = "The detection of structural zeros")
View(tab_zero)
#write.table(tab_zero, file = "~/Data/Output_ANCOMBC2/Tomicro_ANCOMBC2_All_zeros_phylum.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)
```

```{r}
#ANCOMBC primary result
#Result from the ANCOM-BC log-linear model to determine taxa that are differentially abundant according to the covariate of interest. 
#Angegeben ist immer der jeweilige Wert im Vergleich zur 1. Gruppe: Phyllo und Rhizo im Vgl zu Endo, Soil B im Vgl. zu Soil A, Healthy im Vgl. zu diseased
#It contains: 
#1) log fold changes (lfc); 
#2) standard errors(se); 
#3) test statistics(W); 
#4) p-values(p); 
#5) adjusted p-values(q); 
#6) indicators whether the taxon is differentially abundant (TRUE) or not (FALSE) (diff).
#7) if the taxon passed the sensitivity analysis (ss) when adding pseudo counts (= no change in significance independent of pseudocount addition = TRUE) 
res_prim = output$res
View(res_prim)
#write.table(res_prim, file = "~/Data/Output_ANCOMBC2/Tomicro_ANCOMBC2_All_res_prim_phylum.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)

```

```{r}
##ANCOM-BC2 global test of taxa with differential abundance across the “RU”, “HG”, and “EH” categories.
res_global = output$res_global
View(res_global)
#write.table(res_global, file = "~/Data/Output_ANCOMBC2/Tomicro_ANCOMBC2_All_res_global_phylum.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)
```

```{r}
##ANCOM-BC2 multiple pairwise comparisons 
##identify taxa that exhibit differential abundance between any two groups within a set of three or more experimental groups, all while maintaining control over the mdFDR.
res_pair = output$res_pair
View(res_pair)
#write.table(res_pair, file = "~/Data/Output_ANCOMBC2/Tomicro_ANCOMBC2_All_res_pair_phylum.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)

```

```{r}
##ANCOM-BC2 multiple pairwise comparisons against a pre-specified group (Dunnet's test) 
#The Dunnett’s test is tailored for comparing multiple experimental groups against a control or reference group. ANCOM-BC2 Dunnett’s type of test applies this framework but also controls the mdFDR. 
#It’s essential to highlight that ANCOM-BC2’s primary results control for multiple testing across taxa but not for multiple comparisons between groups. As such, unlike the ANCOM-BC2 Dunnett’s test, the primary output doesn’t control the mdFDR.
res_dunn = output$res_dunn
View(res_dunn)
#write.table(res_dunn, file = "~/Data/Output_ANCOMBC2/Tomicro_ANCOMBC2_All_res_dunnet_phylum.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)
```

#Subsets for compartments
Rhizo (1783 ASVs)
```{r}
Tomicro_Rhizo = subset_samples(Tomicro, Compartment == "rhizosphere")
sample_data(Tomicro_Rhizo)

#filter for all 0 rows
otu_table(Tomicro_Rhizo)
ASV_df <- as.data.frame(otu_table(Tomicro_Rhizo))#Extract ASV table
rows_to_keep <- rowSums(ASV_df) != 0# Find rows where all counts are zero
filtered_ASV_df <- ASV_df[rows_to_keep, ]# Filter the OTU table
filtered_ASV_mat <- as.matrix(filtered_ASV_df)# Convert back to a matrix if needed
otu_table(Tomicro_Rhizo) <- otu_table(filtered_ASV_mat, taxa_are_rows = TRUE)
otu_table(Tomicro_Rhizo)

Tomicro_Rhizo_tse <- mia::makeTreeSummarizedExperimentFromPhyloseq(Tomicro_Rhizo)
print(Tomicro_Rhizo_tse)
```

```{r}
#run anbombc2 Rhizo
set.seed(2608)

output = ancombc2(data = Tomicro_Rhizo_tse, assay_name = "counts", tax_level = "phylum",
                  fix_formula = "Soil.origin+Plant.condition", 
                  rand_formula = NULL,
                  p_adj_method = "hochberg", 
                  group = "Soil.origin", 
                  alpha = 0.05, n_cl = 2, 
                  struc_zero = TRUE,
                  global = TRUE, pairwise = TRUE, 
                  dunnet = TRUE, trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                      verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  #lme_control = NULL, 
                  mdfdr_control = list(fwer_ctrl_method = "hochberg", B = 100), 
                  trend_control = NULL)


res_prim = output$res
View(res_prim)
#write.table(res_prim, file = "~/Data/Output_ANCOMBC2/Tomicro_Rhizo_ANCOMBC2_soil_condition_res_prim_ASV.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)

#detection of structural zeros (taxon presence/absence) presence = FALSE, absence = TRUE
tab_zero = output$zero_ind
tab_zero %>%
  datatable(caption = "The detection of structural zeros")
View(tab_zero)
res_prim_zero <- full_join(tab_zero,res_prim,  by = "taxon")
View(res_prim_zero)
write.table(res_prim_zero, file = "~/Data/Output_ANCOMBC2/Tomicro_Rhizo_ANCOMBC2_soil_zeros_Soil_condition_res_prim_phylum.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)
```

Phyllo (713 ASVs)
```{r}
Tomicro_Phyllo = subset_samples(Tomicro, Compartment == "phyllosphere")
sample_data(Tomicro_Phyllo)

#filter for all 0 rows
otu_table(Tomicro_Phyllo)
ASV_df <- as.data.frame(otu_table(Tomicro_Phyllo))#Extract ASV table
rows_to_keep <- rowSums(ASV_df) != 0# Find rows where all counts are zero
filtered_ASV_df <- ASV_df[rows_to_keep, ]# Filter the OTU table
filtered_ASV_mat <- as.matrix(filtered_ASV_df)# Convert back to a matrix if needed
otu_table(Tomicro_Phyllo) <- otu_table(filtered_ASV_mat, taxa_are_rows = TRUE)
otu_table(Tomicro_Phyllo)

Tomicro_Phyllo_tse <- mia::makeTreeSummarizedExperimentFromPhyloseq(Tomicro_Phyllo)
print(Tomicro_Phyllo_tse)
```
```{r}
#run anbombc2 Phyllo
set.seed(2608)

output = ancombc2(data = Tomicro_Phyllo_tse, assay_name = "counts", tax_level = "ASV",
                  fix_formula = "Soil.origin+Plant.condition", 
                  rand_formula = NULL,
                  p_adj_method = "hochberg", 
                  group = "Soil.origin", 
                  alpha = 0.05, n_cl = 2, 
                  struc_zero = TRUE,
                  global = TRUE, pairwise = TRUE, 
                  dunnet = TRUE, trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                      verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  #lme_control = NULL, 
                  mdfdr_control = list(fwer_ctrl_method = "hochberg", B = 100), 
                  trend_control = NULL)


res_prim = output$res
View(res_prim)
#write.table(res_prim, file = "~/Data/Output_ANCOMBC2/Tomicro_Phyllo_ANCOMBC2_soil_condition_res_prim_ASV.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)

#detection of structural zeros (taxon presence/absence) presence = FALSE, absence = TRUE
tab_zero = output$zero_ind
tab_zero %>%
  datatable(caption = "The detection of structural zeros")
View(tab_zero)
res_prim_zero <- full_join(tab_zero,res_prim,  by = "taxon")
View(res_prim_zero)
#write.table(res_prim_zero, file = "~/Data/Output_ANCOMBC2/Tomicro_Phyllo_ANCOMBC2_soil_zeros_Soil_condition_res_prim_ASV.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)
```

Endo (551 ASVs)
```{r}
Tomicro_Endo = subset_samples(Tomicro, Compartment == "endosphere")
sample_data(Tomicro_Endo)

#filter for all 0 rows
otu_table(Tomicro_Endo)
ASV_df <- as.data.frame(otu_table(Tomicro_Endo))#Extract ASV table
rows_to_keep <- rowSums(ASV_df) != 0# Find rows where all counts are zero
filtered_ASV_df <- ASV_df[rows_to_keep, ]# Filter the OTU table
filtered_ASV_mat <- as.matrix(filtered_ASV_df)# Convert back to a matrix if needed
otu_table(Tomicro_Endo) <- otu_table(filtered_ASV_mat, taxa_are_rows = TRUE)
otu_table(Tomicro_Endo)

Tomicro_Endo_tse <- mia::makeTreeSummarizedExperimentFromPhyloseq(Tomicro_Endo)
print(Tomicro_Endo_tse)
```

```{r}
#run anbombc2 Endo
set.seed(2608)

output = ancombc2(data = Tomicro_Endo_tse, assay_name = "counts", tax_level = "ASV",
                  fix_formula = "Soil.origin+Plant.condition", 
                  rand_formula = NULL,
                  p_adj_method = "hochberg", 
                  group = "Soil.origin", 
                  alpha = 0.05, n_cl = 2, 
                  struc_zero = TRUE,
                  global = TRUE, pairwise = TRUE, 
                  dunnet = TRUE, trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                      verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  #lme_control = NULL, 
                  mdfdr_control = list(fwer_ctrl_method = "hochberg", B = 100), 
                  trend_control = NULL)


res_prim = output$res
View(res_prim)
#write.table(res_prim, file = "~/Data/Output_ANCOMBC2/Tomicro_Phyllo_ANCOMBC2_soil_condition_res_prim_ASV.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)

#detection of structural zeros (taxon presence/absence) presence = FALSE, absence = TRUE
tab_zero = output$zero_ind
tab_zero %>%
  datatable(caption = "The detection of structural zeros")
View(tab_zero)
res_prim_zero <- full_join(tab_zero,res_prim,  by = "taxon")
View(res_prim_zero)
write.table(res_prim_zero, file = "~/Data/Output_ANCOMBC2/Tomicro_Endo_ANCOMBC2_soil_zeros_Soil_condition_res_prim_ASV.csv", append = FALSE, sep = " ", dec = ".", row.names = TRUE, col.names = TRUE)
```

